# Generated by Django 6.0.4 on 2026-09-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_activationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Lecteur'), ('editor', 'Éditeur'), ('admin', 'Administrateur')], default='viewer', max_length=20, verbose_name='Responsabilité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Compte Principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaborator_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur invité')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('main_account', 'user'), name='unique_collaborator_invitation')],
            },
        ),
    ]