# Generated by Django 6.0.4 on 2026-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_collaboratorinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
