# Generated by Django 6.0.4 on 2026-10-05 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('PERSONNE_PHYSIQUE', 'Personne Physique'), ('PERSONNE_MORALE', 'Personne Morale')], max_length=20, verbose_name='Type de client')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PROSPECT', 'Prospect'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('reference_client', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence client')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(blank=True, max_length=100, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=50, verbose_name='Forme juridique')),
                ('numero_rccm', models.CharField(blank=True, max_length=50, verbose_name='Numéro RCCM')),
                ('numero_cc', models.CharField(blank=True, max_length=50, verbose_name='Numéro Compte Contribuable')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital social')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('telephone_1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+225XXXXXXXXXX' ou 'XXXXXXXXXX'", regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone 1')),
                ('telephone_2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+225XXXXXXXXXX' ou 'XXXXXXXXXX'", regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('representant_legal_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du représentant légal')),
                ('representant_legal_fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction du représentant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_premier_contact', models.DateField(default=django.utils.timezone.now, verbose_name='Date premier contact')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur le client', verbose_name='Notes')),
                ('charge_de_clientele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_geres', to=settings.AUTH_USER_MODEL, verbose_name='Chargé de clientèle')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['reference_client'], name='Client_clie_referen_60959d_idx'), models.Index(fields=['type_client', 'statut'], name='Client_clie_type_cl_4cec0e_idx'), models.Index(fields=['raison_sociale'], name='Client_clie_raison__2dea3d_idx'), models.Index(fields=['nom', 'prenoms'], name='Client_clie_nom_4c004a_idx')],
            },
        ),
    ]
