# Generated by Django 6.0.4 on 2026-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
    ]
