# Generated by Django 6.0.4 on 2026-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_client_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Dans la corbeille'),
        ),
    ]
